// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejuqrvgddhhktzymtsnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqdXFydmdkZGhoa3R6eW10c25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTU1NjIsImV4cCI6MjA2MTE3MTU2Mn0.mkZr_9a7i0ZCYOM-jtJhI_OOeOQDmaSFfwVAT1rBe70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);